### ISSUE TITLE
NPM: please publish a non-empty version!

### ISSUE THREAD

**Issue by danielbeardsley** [aaroncraigongithub/useSharedState#2]
The published npm package is totally empty (except for the package json). Please release a version (perhaps 1.0?) that actually has the source.

**Comment by aaroncraigongithub** [comment]
I've sort of gotten swamped with work and left this by the wayside -- thanks for letting me know there's at least one person who wants to use this library!

I'll work on a v1 and update here when it's published :)

**Comment by aaroncraigongithub** [comment]
I've published a first version here:
https://www.npmjs.com/package/hook-shared-state

Please note that someone has published an empty package with the same name `use-shared-state` so I've change the NPM package name to `hook-shared-state`.
